"""添加表和字段注释

Revision ID: e211a05619a6
Revises: 002
Create Date: 2025-04-03 15:01:35.076022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e211a05619a6'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='附加元数据，存储为JSON'))
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               comment='消息ID',
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               comment='关联的会话ID',
               existing_nullable=False)
    op.alter_column('chat_messages', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='消息来源，如user或agent',
               existing_nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('chat_messages', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='消息类型，如TextMessage、ImageMessage等',
               existing_nullable=False)
    op.alter_column('chat_messages', 'thought',
               existing_type=sa.TEXT(),
               comment='思考过程，仅适用于智能体消息',
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'models_usage',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='模型使用情况，如tokens、费用等',
               existing_nullable=True)
    op.drop_index('ix_chat_messages_created_at', table_name='chat_messages')
    op.drop_index('ix_chat_messages_session_id', table_name='chat_messages')
    op.create_table_comment(
        'chat_messages',
        '聊天消息表',
        existing_comment=None,
        schema=None
    )
    op.drop_column('chat_messages', 'metadata')
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='会话名称',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'agent_state',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='智能体状态，存储为JSON',
               existing_nullable=True)
    op.drop_index('ix_chat_sessions_created_at', table_name='chat_sessions')
    op.create_table_comment(
        'chat_sessions',
        '聊天会话表',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'chat_sessions',
        existing_comment='聊天会话表',
        schema=None
    )
    op.create_index('ix_chat_sessions_created_at', 'chat_sessions', ['created_at'], unique=False)
    op.alter_column('chat_sessions', 'agent_state',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='智能体状态，存储为JSON',
               existing_nullable=True)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='会话名称',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.add_column('chat_messages', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table_comment(
        'chat_messages',
        existing_comment='聊天消息表',
        schema=None
    )
    op.create_index('ix_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.alter_column('chat_messages', 'models_usage',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='模型使用情况，如tokens、费用等',
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'thought',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='思考过程，仅适用于智能体消息',
               existing_nullable=True)
    op.alter_column('chat_messages', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='消息类型，如TextMessage、ImageMessage等',
               existing_nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('chat_messages', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='消息来源，如user或agent',
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联的会话ID',
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='消息ID',
               existing_nullable=False)
    op.drop_column('chat_messages', 'meta_data')
    # ### end Alembic commands ###
